// Package models holds persisted control-plane entities and deployment status constants.
// IDs are opaque hex strings generated by the repository layer.
package models

import (
	"strings"
	"time"
)

// Deployment lifecycle values stored in deployments.status (see SQL CHECK constraint).
const (
	DeploymentQueued   = "QUEUED"
	DeploymentBuilding = "BUILDING"
	DeploymentSuccess  = "SUCCESS"
	DeploymentFailed   = "FAILED"
)

const (
	SSLStatusPending = "PENDING"
	SSLStatusActive  = "ACTIVE"
	SSLStatusError   = "ERROR"
)

// DeployRuntime values for projects.deploy_runtime (HostForge → Nixpacks worktree config).
const (
	DeployRuntimeAuto = "auto"
	DeployRuntimeBun  = "bun"
)

// ProjectEnvVar is metadata for one encrypted env entry (no plaintext).
type ProjectEnvVar struct {
	ID         string
	ProjectID  string
	Key        string
	ValueLast4 string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// ProjectEnvSealed holds key + ciphertext for deploy-time decryption.
type ProjectEnvSealed struct {
	Key     string
	ValueCT []byte
}

// Project is a Git source (repo + branch) that deployments belong to.
type Project struct {
	ID      string
	Name    string
	RepoURL string
	Branch  string // empty means remote default branch at creation time
	// DeployRuntime selects how HostForge generates a worktree-local nixpacks.toml before build (auto | bun).
	DeployRuntime    string
	DeployInstallCmd string
	DeployBuildCmd   string
	DeployStartCmd   string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// Deployment is one build/run attempt for a project.
type Deployment struct {
	ID           string
	ProjectID    string
	Status       string
	CommitHash   string // optional; set when known (e.g. post-clone in a later phase)
	LogsPath     string // optional; build log artifact path (Phase 5+)
	ImageRef     string // Docker image reference built for this attempt
	Worktree     string // on-disk clone path for this deploy
	ErrorMessage string // set when Status is DeploymentFailed
	// StackKind is a stable slug from nixpacks plan (e.g. node, node_vite, node_next, go) for UI icons; empty if not captured.
	StackKind string
	// StackLabel is a short human summary (e.g. "Node · SPA"); empty if not captured.
	StackLabel string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Container records a running Docker instance for a successful deployment.
type Container struct {
	ID                string
	DeploymentID      string
	DockerContainerID string // full ID from Docker Engine
	InternalPort      int    // app port inside the container (matches published port mapping)
	HostPort          int    // published port on 127.0.0.1
	Status            string // e.g. RUNNING
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Domain links a public hostname to a project.
type Domain struct {
	ID               string
	ProjectID        string
	DomainName       string
	SSLStatus        string
	LastCertMessage  string // operator summary from optional cert poll (not ssl_status / route sync)
	CertCheckedAtRaw string // RFC3339 from DB; empty if never polled
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// CertCheckedAt returns CertCheckedAtRaw parsed as time, or zero if unset/invalid.
func (d Domain) CertCheckedAt() time.Time {
	raw := strings.TrimSpace(d.CertCheckedAtRaw)
	if raw == "" {
		return time.Time{}
	}
	t, err := time.Parse(time.RFC3339, raw)
	if err != nil {
		return time.Time{}
	}
	return t
}

// DomainRoute is a resolved Caddy route candidate from domain to local upstream port.
type DomainRoute struct {
	Domain
	HostPort int
}

// DeployStepRecord is one persisted deploy or system observability span (SQLite observability UI).
type DeployStepRecord struct {
	DeploymentID string
	ProjectID    string
	RequestID    string
	Step         string
	Status       string // ok | failed
	DurationMS   int64
	ErrorCode    string
	StartedAt    time.Time
	EndedAt      time.Time
}

// HTTPRequestRecord is one sampled HTTP request line for the observability UI.
type HTTPRequestRecord struct {
	RequestID  string
	Method     string
	Path       string
	Status     int
	DurationMS int64
	StartedAt  time.Time
}
