// Package models holds persisted control-plane entities and deployment status constants.
// IDs are opaque hex strings generated by the repository layer.
package models

import "time"

// Deployment lifecycle values stored in deployments.status (see SQL CHECK constraint).
const (
	DeploymentQueued   = "QUEUED"
	DeploymentBuilding = "BUILDING"
	DeploymentSuccess  = "SUCCESS"
	DeploymentFailed   = "FAILED"
)

const (
	SSLStatusPending = "PENDING"
	SSLStatusActive  = "ACTIVE"
	SSLStatusError   = "ERROR"
)

// Project is a Git source (repo + branch) that deployments belong to.
type Project struct {
	ID        string
	Name      string
	RepoURL   string
	Branch    string // empty means remote default branch at creation time
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Deployment is one build/run attempt for a project.
type Deployment struct {
	ID           string
	ProjectID    string
	Status       string
	CommitHash   string // optional; set when known (e.g. post-clone in a later phase)
	LogsPath     string // optional; build log artifact path (Phase 5+)
	ImageRef     string // Docker image reference built for this attempt
	Worktree     string // on-disk clone path for this deploy
	ErrorMessage string // set when Status is DeploymentFailed
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Container records a running Docker instance for a successful deployment.
type Container struct {
	ID                string
	DeploymentID      string
	DockerContainerID string // full ID from Docker Engine
	InternalPort      int    // app port inside the container (matches published port mapping)
	HostPort          int    // published port on 127.0.0.1
	Status            string // e.g. RUNNING
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Domain links a public hostname to a project.
type Domain struct {
	ID         string
	ProjectID  string
	DomainName string
	SSLStatus  string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// DomainRoute is a resolved Caddy route candidate from domain to local upstream port.
type DomainRoute struct {
	Domain
	HostPort int
}
