package caddy

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// Route maps a domain to a local upstream host port.
type Route struct {
	Domain   string
	HostPort int
}

// SyncOptions controls generated config output and caddy apply behavior.
type SyncOptions struct {
	CaddyBin      string
	GeneratedPath string
	RootConfig    string
	Routes        []Route
}

// SyncResult describes the generated output path and whether caddy was reloaded.
type SyncResult struct {
	GeneratedPath string
	Applied       bool
}

// Sync renders routes, writes generated config atomically, validates, then reloads caddy.
func Sync(ctx context.Context, opts SyncOptions) (SyncResult, error) {
	if strings.TrimSpace(opts.GeneratedPath) == "" {
		return SyncResult{}, fmt.Errorf("generated path is required")
	}
	if strings.TrimSpace(opts.RootConfig) == "" {
		return SyncResult{}, fmt.Errorf("root config path is required")
	}
	bin := strings.TrimSpace(opts.CaddyBin)
	if bin == "" {
		bin = "caddy"
	}
	content := RenderConfig(opts.Routes)
	if err := writeAtomic(opts.GeneratedPath, []byte(content)); err != nil {
		return SyncResult{}, err
	}
	if err := runCaddy(ctx, bin, "validate", "--config", opts.RootConfig); err != nil {
		return SyncResult{GeneratedPath: opts.GeneratedPath}, fmt.Errorf("caddy validate: %w", err)
	}
	if err := runCaddy(ctx, bin, "reload", "--config", opts.RootConfig); err != nil {
		return SyncResult{GeneratedPath: opts.GeneratedPath}, fmt.Errorf("caddy reload: %w", err)
	}
	return SyncResult{GeneratedPath: opts.GeneratedPath, Applied: true}, nil
}

// RenderConfig converts routes into caddyfile server blocks.
func RenderConfig(routes []Route) string {
	filtered := make([]Route, 0, len(routes))
	for _, route := range routes {
		if route.HostPort <= 0 || strings.TrimSpace(route.Domain) == "" {
			continue
		}
		route.Domain = strings.TrimSpace(route.Domain)
		filtered = append(filtered, route)
	}
	sort.Slice(filtered, func(i, j int) bool {
		return filtered[i].Domain < filtered[j].Domain
	})

	var b strings.Builder
	b.WriteString("# generated by hostforge; do not edit manually\n\n")
	for _, route := range filtered {
		fmt.Fprintf(&b, "%s {\n", route.Domain)
		fmt.Fprintf(&b, "    reverse_proxy 127.0.0.1:%d\n", route.HostPort)
		b.WriteString("}\n\n")
	}
	return b.String()
}

func writeAtomic(path string, body []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir caddy dir: %w", err)
	}
	tmp, err := os.CreateTemp(dir, ".hostforge-caddy-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp caddy file: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if _, err := tmp.Write(body); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temp caddy file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp caddy file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace caddy config: %w", err)
	}
	return nil
}

func runCaddy(ctx context.Context, bin string, args ...string) error {
	cmd := exec.CommandContext(ctx, bin, args...)
	var combined bytes.Buffer
	cmd.Stdout = &combined
	cmd.Stderr = &combined
	if err := cmd.Run(); err != nil {
		out := strings.TrimSpace(combined.String())
		if out == "" {
			return err
		}
		return fmt.Errorf("%w: %s", err, out)
	}
	return nil
}
