package caddy

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestIsCaddyAdminUnreachable(t *testing.T) {
	err := fmt.Errorf(`Error: sending configuration to instance: performing request: Post "http://localhost:2019/load": dial tcp 127.0.0.1:2019: connect: connection refused`)
	if !isCaddyAdminUnreachable(err) {
		t.Fatal("expected admin unreachable")
	}
	if isCaddyAdminUnreachable(fmt.Errorf("caddy validate: some parse error")) {
		t.Fatal("unexpected match")
	}
	if isCaddyAdminUnreachable(nil) {
		t.Fatal("nil")
	}
}

func TestWriteAtomicMakesGeneratedFileGroupReadable(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Windows does not expose POSIX file mode bits")
	}
	path := filepath.Join(t.TempDir(), "hostforge.caddy")
	if err := writeAtomic(path, []byte("example.com {}\n")); err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := info.Mode().Perm(), os.FileMode(0o640); got != want {
		t.Fatalf("generated file permissions = %o, want %o", got, want)
	}
}

func TestRenderBootstrapConfigIsHTTPSOnly(t *testing.T) {
	got := RenderBootstrapConfig("203.0.113.4", 8443)
	for _, want := range []string{"auto_https disable_redirects", "https://203.0.113.4:8443", "tls", "reverse_proxy 127.0.0.1:8080", "header_up X-Forwarded-For {remote_host}"} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in %s", want, got)
		}
	}
	if strings.Contains(got, "http://") {
		t.Fatal("bootstrap must not render HTTP")
	}
}

func TestRenderPermanentControlPlaneConfigIsManagedSnippet(t *testing.T) {
	got := RenderPermanentControlPlaneConfig("hostforge.example.com")
	for _, want := range []string{"generated by hostforge onboarding", "https://hostforge.example.com", "tls", "reverse_proxy 127.0.0.1:8080", "header_up X-Forwarded-For {remote_host}"} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in %s", want, got)
		}
	}
	if strings.Contains(got, "import ") || strings.Contains(got, "auto_https") {
		t.Fatalf("control-plane snippet must not own root config directives: %s", got)
	}
}

func TestRenderConfigCertificateOnlyDomainDoesNotProxyDatabaseTraffic(t *testing.T) {
	config := RenderConfigWithCertificateDomains(nil, []string{"postgres.apps.example.test"})
	if !strings.Contains(config, "https://postgres.apps.example.test") || !strings.Contains(config, "respond /hostforge-certificate-probe 204") {
		t.Fatalf("certificate-only site missing:\n%s", config)
	}
	if strings.Contains(config, "\n    tls\n") {
		t.Fatalf("certificate-only site must rely on automatic HTTPS for broad Caddy compatibility:\n%s", config)
	}
	if strings.Contains(config, "reverse_proxy") || strings.Contains(config, ":5432") {
		t.Fatalf("Caddy was incorrectly placed in the PostgreSQL data path:\n%s", config)
	}
}

func TestReplaceManagedConfigUpdatesImportedSnippet(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("test uses a POSIX shell stub")
	}
	dir := t.TempDir()
	root := filepath.Join(dir, "Caddyfile")
	managed := filepath.Join(dir, "control-plane.caddy")
	bin := filepath.Join(dir, "caddy")
	if err := os.WriteFile(root, []byte("import "+managed+"\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(managed, []byte("old.example.com {}\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(bin, []byte("#!/bin/sh\nexit 0\n"), 0o750); err != nil {
		t.Fatal(err)
	}

	if err := ReplaceManagedConfig(t.Context(), bin, managed, root, "new.example.com {}\n"); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(managed)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "new.example.com {}\n" {
		t.Fatalf("managed config = %q", got)
	}
}

func TestReplaceManagedConfigRestoresSnippetWhenValidationFails(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("test uses a POSIX shell stub")
	}
	dir := t.TempDir()
	root := filepath.Join(dir, "Caddyfile")
	managed := filepath.Join(dir, "control-plane.caddy")
	bin := filepath.Join(dir, "caddy")
	if err := os.WriteFile(root, []byte("import "+managed+"\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(managed, []byte("old.example.com {}\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(bin, []byte("#!/bin/sh\nexit 1\n"), 0o750); err != nil {
		t.Fatal(err)
	}

	if err := ReplaceManagedConfig(t.Context(), bin, managed, root, "broken.example.com {\n"); err == nil {
		t.Fatal("expected validation failure")
	}
	got, err := os.ReadFile(managed)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "old.example.com {}\n" {
		t.Fatalf("managed config was not restored: %q", got)
	}
}
