package caddy

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestIsCaddyAdminUnreachable(t *testing.T) {
	err := fmt.Errorf(`Error: sending configuration to instance: performing request: Post "http://localhost:2019/load": dial tcp 127.0.0.1:2019: connect: connection refused`)
	if !isCaddyAdminUnreachable(err) {
		t.Fatal("expected admin unreachable")
	}
	if isCaddyAdminUnreachable(fmt.Errorf("caddy validate: some parse error")) {
		t.Fatal("unexpected match")
	}
	if isCaddyAdminUnreachable(nil) {
		t.Fatal("nil")
	}
}

func TestWriteAtomicMakesGeneratedFileGroupReadable(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Windows does not expose POSIX file mode bits")
	}
	path := filepath.Join(t.TempDir(), "hostforge.caddy")
	if err := writeAtomic(path, []byte("example.com {}\n")); err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := info.Mode().Perm(), os.FileMode(0o640); got != want {
		t.Fatalf("generated file permissions = %o, want %o", got, want)
	}
}

// A raw IP cannot be issued a publicly trusted certificate, so the bootstrap
// route has to name Caddy's internal CA explicitly. It must also name it as
// `tls internal`, never a bare `tls`: Caddy 2.11 rejects the argumentless
// directive, and the generated file is fed straight to `caddy validate` --
// an invalid one aborted the installer before it ever started HostForge.
func TestRenderBootstrapConfigUsesTheInternalCA(t *testing.T) {
	got := RenderBootstrapConfig("203.0.113.4", 8443)
	for _, want := range []string{"auto_https disable_redirects", "https://203.0.113.4:8443", "tls internal", "reverse_proxy 127.0.0.1:8080", "header_up X-Forwarded-For {remote_host}"} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in %s", want, got)
		}
	}
	if strings.Contains(got, "\ttls\n") {
		t.Fatalf("a bare tls directive does not parse in Caddy 2.11:\n%s", got)
	}
	if strings.Contains(got, "http://") {
		t.Fatal("bootstrap must not render HTTP")
	}
}

// The permanent route names a real hostname, so automatic HTTPS obtains a
// publicly trusted certificate for it. It must emit no tls directive at all:
// a bare one fails validation, and `tls internal` would pin the control plane
// to a self-signed certificate and warn every visitor forever.
func TestRenderPermanentControlPlaneConfigLeavesTLSToAutomaticHTTPS(t *testing.T) {
	got := RenderPermanentControlPlaneConfig("hostforge.example.com")
	for _, want := range []string{"generated by hostforge onboarding", "https://hostforge.example.com", "reverse_proxy 127.0.0.1:8080", "header_up X-Forwarded-For {remote_host}"} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in %s", want, got)
		}
	}
	if strings.Contains(got, "tls") {
		t.Fatalf("the permanent route must rely on automatic HTTPS, not a tls directive:\n%s", got)
	}
	if strings.Contains(got, "import ") || strings.Contains(got, "auto_https") {
		t.Fatalf("control-plane snippet must not own root config directives: %s", got)
	}
}

func TestRenderConfigCertificateOnlyDomainDoesNotProxyDatabaseTraffic(t *testing.T) {
	config := RenderConfigWithCertificateDomains(nil, []string{"postgres.apps.example.test"})
	if !strings.Contains(config, "https://postgres.apps.example.test") || !strings.Contains(config, "respond /hostforge-certificate-probe 204") {
		t.Fatalf("certificate-only site missing:\n%s", config)
	}
	if strings.Contains(config, "\n    tls\n") {
		t.Fatalf("certificate-only site must rely on automatic HTTPS for broad Caddy compatibility:\n%s", config)
	}
	if strings.Contains(config, "reverse_proxy") || strings.Contains(config, ":5432") {
		t.Fatalf("Caddy was incorrectly placed in the PostgreSQL data path:\n%s", config)
	}
}

func TestReplaceManagedConfigUpdatesImportedSnippet(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("test uses a POSIX shell stub")
	}
	dir := t.TempDir()
	root := filepath.Join(dir, "Caddyfile")
	managed := filepath.Join(dir, "control-plane.caddy")
	bin := filepath.Join(dir, "caddy")
	if err := os.WriteFile(root, []byte("import "+managed+"\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(managed, []byte("old.example.com {}\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(bin, []byte("#!/bin/sh\nexit 0\n"), 0o750); err != nil {
		t.Fatal(err)
	}

	if err := ReplaceManagedConfig(t.Context(), bin, managed, root, "new.example.com {}\n"); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(managed)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "new.example.com {}\n" {
		t.Fatalf("managed config = %q", got)
	}
}

func TestReplaceManagedConfigRestoresSnippetWhenValidationFails(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("test uses a POSIX shell stub")
	}
	dir := t.TempDir()
	root := filepath.Join(dir, "Caddyfile")
	managed := filepath.Join(dir, "control-plane.caddy")
	bin := filepath.Join(dir, "caddy")
	if err := os.WriteFile(root, []byte("import "+managed+"\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(managed, []byte("old.example.com {}\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(bin, []byte("#!/bin/sh\nexit 1\n"), 0o750); err != nil {
		t.Fatal(err)
	}

	if err := ReplaceManagedConfig(t.Context(), bin, managed, root, "broken.example.com {\n"); err == nil {
		t.Fatal("expected validation failure")
	}
	got, err := os.ReadFile(managed)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "old.example.com {}\n" {
		t.Fatalf("managed config was not restored: %q", got)
	}
}

func TestValidateSiteBlockAcceptsAWellFormedDomain(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("test uses a POSIX shell stub")
	}
	bin := filepath.Join(t.TempDir(), "caddy")
	if err := os.WriteFile(bin, []byte("#!/bin/sh\nexit 0\n"), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := ValidateSiteBlock(t.Context(), bin, "api.example.com", 3000); err != nil {
		t.Fatalf("expected a well-formed domain to validate, got %v", err)
	}
}

// A domain with no upstream yet (the common case at add time -- the target
// service usually has no successful deployment) must still be checked for
// syntax. hostPort <= 0 must not silently skip validation.
func TestValidateSiteBlockValidatesEvenWithNoKnownUpstreamPort(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("test uses a POSIX shell stub")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "caddy")
	captured := filepath.Join(dir, "captured.caddyfile")
	// Copies whatever config validate was asked to check, so the test can
	// assert a domain block was actually written -- not merely that the
	// stub was invoked. Walks argv to find the value after --config,
	// rather than assuming a fixed position (--adapter follows it).
	script := "#!/bin/sh\nprev=\"\"\nfor a; do\n  if [ \"$prev\" = \"--config\" ]; then cfg=\"$a\"; fi\n  prev=\"$a\"\ndone\ncp \"$cfg\" " + captured + "\nexit 1\n"
	if err := os.WriteFile(bin, []byte(script), 0o750); err != nil {
		t.Fatal(err)
	}
	_ = ValidateSiteBlock(t.Context(), bin, "no-upstream-yet.example.com", 0)
	got, err := os.ReadFile(captured)
	if err != nil {
		t.Fatalf("validate was not invoked with a config file: %v", err)
	}
	if !strings.Contains(string(got), "no-upstream-yet.example.com") {
		t.Fatalf("rendered config missing the domain despite hostPort<=0:\n%s", got)
	}
}

func TestValidateSiteBlockRejectionIsErrValidationFailed(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("test uses a POSIX shell stub")
	}
	bin := filepath.Join(t.TempDir(), "caddy")
	if err := os.WriteFile(bin, []byte("#!/bin/sh\necho 'parse error' >&2\nexit 1\n"), 0o750); err != nil {
		t.Fatal(err)
	}
	err := ValidateSiteBlock(t.Context(), bin, "bad domain", 3000)
	if err == nil {
		t.Fatal("expected an error")
	}
	if !errors.Is(err, ErrValidationFailed) {
		t.Fatalf("error does not wrap ErrValidationFailed: %v", err)
	}
	if !strings.Contains(err.Error(), "parse error") {
		t.Fatalf("validator output not preserved in error: %v", err)
	}
}

func TestSyncValidationFailureIsErrValidationFailed(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("test uses a POSIX shell stub")
	}
	dir := t.TempDir()
	root := filepath.Join(dir, "Caddyfile")
	if err := os.WriteFile(root, []byte(""), 0o640); err != nil {
		t.Fatal(err)
	}
	bin := filepath.Join(dir, "caddy")
	if err := os.WriteFile(bin, []byte("#!/bin/sh\nexit 1\n"), 0o750); err != nil {
		t.Fatal(err)
	}
	_, err := Sync(t.Context(), SyncOptions{
		CaddyBin: bin, GeneratedPath: filepath.Join(dir, "hostforge.caddy"), RootConfig: root,
	})
	if err == nil {
		t.Fatal("expected an error")
	}
	if !errors.Is(err, ErrValidationFailed) {
		t.Fatalf("a validate failure from Sync must wrap ErrValidationFailed so callers can tell it apart from a reload failure: %v", err)
	}
}
