package services

import (
	"fmt"
	"strings"

	"github.com/hostforge/hostforge/internal/models"
)

const maxDeployCommandRunes = 4096

// ValidateDeployFields normalizes runtime and command strings for API persistence.
// errCode is a stable machine-oriented token when validation fails (empty means OK).
func ValidateDeployFields(runtime, install, build, start string) (normRuntime, ni, nb, ns string, errCode string) {
	rt := strings.ToLower(strings.TrimSpace(runtime))
	if rt == "" {
		rt = models.DeployRuntimeAuto
	}
	if rt != models.DeployRuntimeAuto && rt != models.DeployRuntimeBun {
		return "", "", "", "", "invalid_deploy_runtime"
	}
	for label, s := range map[string]string{"install_cmd": install, "build_cmd": build, "start_cmd": start} {
		t := strings.TrimSpace(s)
		if strings.ContainsRune(t, '\x00') {
			return "", "", "", "", "deploy_command_invalid"
		}
		if len([]rune(t)) > maxDeployCommandRunes {
			return "", "", "", "", "deploy_command_too_long:" + label
		}
	}
	return rt, strings.TrimSpace(install), strings.TrimSpace(build), strings.TrimSpace(start), ""
}

// RenderWorktreeNixpacksToml builds a nixpacks.toml fragment written into the clone root before `nixpacks build`.
// When write is false, callers should not create or overwrite nixpacks.toml (preserve pure Nixpacks auto-detect).
func RenderWorktreeNixpacksToml(p models.Project) (content string, write bool) {
	rt := strings.ToLower(strings.TrimSpace(p.DeployRuntime))
	if rt == "" {
		rt = models.DeployRuntimeAuto
	}
	install := strings.TrimSpace(p.DeployInstallCmd)
	build := strings.TrimSpace(p.DeployBuildCmd)
	start := strings.TrimSpace(p.DeployStartCmd)

	if rt == models.DeployRuntimeBun {
		if install == "" {
			install = "bun install"
		}
		if build == "" {
			build = "bun run build"
		}
		if start == "" {
			start = "bun run start"
		}
		var b strings.Builder
		b.WriteString("# Generated by HostForge before `nixpacks build` (see README: Bun + Nixpacks).\n")
		b.WriteString("# This file is not committed; it is regenerated each deploy from project settings.\n")
		b.WriteString("# Note: no Bun-only Nixpacks provider line — many CLI versions error with \"Provider bun not found\".\n")
		b.WriteString("# Instead we pin packages in [phases.setup] and Node major via [variables].\n\n")
		b.WriteString("[variables]\n")
		b.WriteString("NIXPACKS_NODE_VERSION = \"20\"\n\n")
		b.WriteString("[phases.setup]\n")
		b.WriteString("nixPkgs = [\"bun\", \"nodejs_20\", \"openssl\"]\n\n")
		b.WriteString("[phases.install]\n")
		fmt.Fprintf(&b, "cmds = [%s]\n\n", tomlStringList([]string{install}))
		b.WriteString("[phases.build]\n")
		fmt.Fprintf(&b, "cmds = [%s]\n\n", tomlStringList([]string{build}))
		b.WriteString("[start]\n")
		fmt.Fprintf(&b, "cmd = %s\n", tomlQuotedString(start))
		return b.String(), true
	}

	if install == "" && build == "" && start == "" {
		return "", false
	}

	var b strings.Builder
	b.WriteString("# Generated by HostForge: partial nixpacks overrides (runtime=auto). See README.\n\n")
	if install != "" {
		b.WriteString("[phases.install]\n")
		fmt.Fprintf(&b, "cmds = [%s]\n\n", tomlStringList([]string{install}))
	}
	if build != "" {
		b.WriteString("[phases.build]\n")
		fmt.Fprintf(&b, "cmds = [%s]\n\n", tomlStringList([]string{build}))
	}
	if start != "" {
		b.WriteString("[start]\n")
		fmt.Fprintf(&b, "cmd = %s\n", tomlQuotedString(start))
	}
	return b.String(), true
}

func tomlStringList(xs []string) string {
	parts := make([]string, 0, len(xs))
	for _, x := range xs {
		parts = append(parts, tomlQuotedString(x))
	}
	return strings.Join(parts, ", ")
}

func tomlQuotedString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&b, "\\u%04x", r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}
