#!/usr/bin/env bash
# Migrates HostForge-owned Caddy roots to imported, service-writable snippets.
# Safe to run repeatedly. Unknown/custom root Caddyfiles are left untouched.
set -euo pipefail

ENV_FILE="${HF_ENV_FILE:-/etc/hostforge/hostforge.env}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "error: Caddy layout migration requires root" >&2
  exit 1
fi
if [[ ! -r "${ENV_FILE}" ]] || ! command -v caddy >/dev/null 2>&1; then
  exit 0
fi

read_env() {
  local key="$1"
  awk -v key="${key}" '
    $0 ~ "^[[:space:]]*" key "=" {
      line=$0
      sub("^[[:space:]]*" key "=", "", line)
      gsub(/\r$/, "", line)
      if ((line ~ /^".*"$/) || (line ~ /^\047.*\047$/)) {
        line=substr(line, 2, length(line)-2)
      }
      print line
      exit
    }
  ' "${ENV_FILE}"
}

ROOT_CONFIG="$(read_env HOSTFORGE_CADDY_ROOT_CONFIG)"
ROUTES_PATH="$(read_env HOSTFORGE_CADDY_GENERATED_PATH)"
CONTROL_PATH="$(read_env HOSTFORGE_CADDY_CONTROL_PLANE_PATH)"
if [[ -z "${ROOT_CONFIG}" ]] || [[ -z "${ROUTES_PATH}" ]] || [[ ! -f "${ROOT_CONFIG}" ]]; then
  exit 0
fi
if [[ -z "${CONTROL_PATH}" ]]; then
  CONTROL_PATH="$(dirname "${ROUTES_PATH}")/control-plane.caddy"
fi

install -d -m 2770 -o root -g caddy "$(dirname "${ROUTES_PATH}")"
install -d -m 2770 -o root -g caddy "$(dirname "${CONTROL_PATH}")"
if [[ ! -e "${ROUTES_PATH}" ]]; then
  install -m 0640 -o root -g caddy /dev/null "${ROUTES_PATH}"
else
  chown root:caddy "${ROUTES_PATH}"
  chmod 0640 "${ROUTES_PATH}"
fi

if grep -Fq "import ${CONTROL_PATH}" "${ROOT_CONFIG}"; then
  if [[ -e "${CONTROL_PATH}" ]]; then
    chown root:caddy "${CONTROL_PATH}"
    chmod 0640 "${CONTROL_PATH}"
  fi
  exit 0
fi

if ! grep -Eq '# HostForge bootstrap:|# generated by hostforge bootstrap|# generated by hostforge onboarding' "${ROOT_CONFIG}"; then
  echo "warning: ${ROOT_CONFIG} is not a recognized HostForge-owned Caddyfile; skipping automatic control-plane migration." >&2
  echo "warning: import ${CONTROL_PATH} from the root Caddyfile and make the snippet writable by the caddy group." >&2
  exit 0
fi

control_tmp="$(mktemp)"
root_tmp="$(mktemp)"
previous_control="$(mktemp)"
had_control=0
cleanup() {
  rm -f "${control_tmp}" "${root_tmp}" "${previous_control}"
}
trap cleanup EXIT

if [[ -f "${CONTROL_PATH}" ]]; then
  cp "${CONTROL_PATH}" "${previous_control}"
  had_control=1
fi

if grep -Eq '# HostForge bootstrap:|# generated by hostforge bootstrap' "${ROOT_CONFIG}"; then
  public_ip="$(read_env HOSTFORGE_BOOTSTRAP_PUBLIC_IP)"
  https_port="$(read_env HOSTFORGE_BOOTSTRAP_HTTPS_PORT)"
  if [[ -z "${public_ip}" ]]; then
    echo "warning: cannot migrate bootstrap Caddy route without HOSTFORGE_BOOTSTRAP_PUBLIC_IP." >&2
    exit 0
  fi
  address="https://${public_ip}"
  if [[ -n "${https_port}" ]] && [[ "${https_port}" != "443" ]]; then
    address="${address}:${https_port}"
  fi
  {
    echo "# generated by hostforge bootstrap; HTTPS only"
    echo "${address} {"
    echo "    tls"
    echo "    reverse_proxy 127.0.0.1:8080"
    echo "}"
  } >"${control_tmp}"
else
  domain="$(sed -nE 's/^[[:space:]]*https:\/\/([^[:space:]\{]+)[[:space:]]*\{.*/\1/p' "${ROOT_CONFIG}" | head -n 1)"
  if [[ -z "${domain}" ]]; then
    echo "warning: cannot determine the current HostForge platform domain from ${ROOT_CONFIG}; skipping migration." >&2
    exit 0
  fi
  {
    echo "# generated by hostforge onboarding"
    echo "https://${domain} {"
    echo "    tls"
    echo "    reverse_proxy 127.0.0.1:8080"
    echo "}"
  } >"${control_tmp}"
fi

{
  echo "{"
  echo "    auto_https disable_redirects"
  echo "}"
  echo
  echo "# HostForge control-plane and deployment routes are managed in writable imports."
  echo "import ${CONTROL_PATH}"
  echo "import ${ROUTES_PATH}"
} >"${root_tmp}"

install -m 0640 -o root -g caddy "${control_tmp}" "${CONTROL_PATH}"
if ! caddy validate --config "${root_tmp}" --adapter caddyfile; then
  if [[ "${had_control}" -eq 1 ]]; then
    install -m 0640 -o root -g caddy "${previous_control}" "${CONTROL_PATH}"
  else
    rm -f "${CONTROL_PATH}"
  fi
  echo "error: migrated Caddy layout did not validate; existing root config was not changed." >&2
  exit 1
fi

root_backup="${ROOT_CONFIG}.hostforge-before-managed-imports"
if [[ ! -e "${root_backup}" ]]; then
  cp -a "${ROOT_CONFIG}" "${root_backup}"
fi
install -m 0644 -o root -g root "${root_tmp}" "${ROOT_CONFIG}"
if ! caddy reload --config "${ROOT_CONFIG}"; then
  cp -a "${root_backup}" "${ROOT_CONFIG}"
  if [[ "${had_control}" -eq 1 ]]; then
    install -m 0640 -o root -g caddy "${previous_control}" "${CONTROL_PATH}"
  else
    rm -f "${CONTROL_PATH}"
  fi
  caddy reload --config "${ROOT_CONFIG}" || true
  echo "error: Caddy rejected the migrated layout; restored the previous root config." >&2
  exit 1
fi

echo "Migrated HostForge Caddy control plane to ${CONTROL_PATH}."
