import { useState } from "react"
import { Link } from "react-router-dom"
import {
  ActivityIcon,
  ArchiveIcon,
  ArrowLeftIcon,
  BookOpenIcon,
  BracketsCurlyIcon,
  CheckCircleIcon,
  CloudArrowUpIcon,
  CodeIcon,
  CubeIcon,
  GithubLogoIcon,
  GlobeIcon,
  HardDrivesIcon,
  InfoIcon,
  KeyIcon,
  LockKeyIcon,
  PasswordIcon,
  PlugsConnectedIcon,
  PulseIcon,
  ShieldCheckIcon,
  SlidersHorizontalIcon,
  TrashIcon,
  UserCircleIcon,
  WarningCircleIcon,
  WebhooksLogoIcon,
  WrenchIcon,
} from "@phosphor-icons/react"

import { Button } from "@/components/ui/button"
import { navigateTo } from "@/navigation"
import "@/settings.css"

type SettingsItem = { id: string; label: string; icon: React.ComponentType<{ size?: number; className?: string }> }

function SettingsLayout({ title, description, back, items, active, onSelect, children }: { title: string; description: string; back?: { label: string; href: string }; items: SettingsItem[]; active: string; onSelect: (id: string) => void; children: React.ReactNode }) {
  return <main className="mx-auto w-full max-w-[1500px] px-4 py-7 sm:px-6 lg:px-8 lg:py-9">{back && <Link to={back.href} className="mb-5 inline-flex items-center gap-2 text-xs font-medium text-muted-foreground hover:text-foreground"><ArrowLeftIcon size={14} />{back.label}</Link>}<div className="mb-8"><h1 className="text-3xl font-semibold tracking-[-0.035em]">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></div><div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="h-fit rounded-xl border bg-card p-2 lg:sticky lg:top-20"><nav className="space-y-1" aria-label={`${title} sections`}>{items.map((item) => { const ItemIcon = item.icon; return <button key={item.id} onClick={() => onSelect(item.id)} className={`flex w-full items-center gap-2.5 rounded-lg px-3 py-2.5 text-left text-xs font-medium ${active === item.id ? "bg-accent text-accent-foreground" : item.id === "danger" ? "text-red-700 hover:bg-red-50" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><ItemIcon size={16} />{item.label}</button> })}</nav></aside><div className="min-w-0">{children}</div></div></main>
}

function Section({ title, description, children, footer }: { title: string; description: string; children: React.ReactNode; footer?: React.ReactNode }) {
  return <section className="overflow-hidden rounded-xl border bg-card"><header className="border-b bg-muted/75 px-5 py-4"><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></header><div className="space-y-5 p-5 sm:p-6">{children}</div>{footer && <footer className="flex justify-end border-t bg-muted/30 px-5 py-4">{footer}</footer>}</section>
}

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold">{label}</span>{children}{hint && <span className="mt-2 block text-[11px] leading-5 text-muted-foreground">{hint}</span>}</label> }
function Toggle({ label, description, defaultOn = false }: { label: string; description: string; defaultOn?: boolean }) { const [on, setOn] = useState(defaultOn); return <div className="flex items-start gap-4 rounded-lg border p-4"><div><p className="text-xs font-semibold">{label}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{description}</p></div><button onClick={() => setOn(!on)} role="switch" aria-checked={on} className={`ml-auto mt-0.5 flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors ${on ? "bg-accent" : "bg-neutral-300"}`}><span className={`size-4 rounded-full bg-white shadow-sm transition-transform ${on ? "translate-x-4" : ""}`} /></button></div> }
function SaveFooter() { return <Button>Save changes</Button> }

const applicationItems: SettingsItem[] = [
  { id: "general", label: "General", icon: SlidersHorizontalIcon },
  { id: "git", label: "Git integration", icon: GithubLogoIcon },
  { id: "environment", label: "Environment", icon: BracketsCurlyIcon },
  { id: "activity", label: "Activity", icon: ActivityIcon },
  { id: "danger", label: "Danger zone", icon: WarningCircleIcon },
]

export function ApplicationSettings() {
  const [active, setActive] = useState("general")
  return <SettingsLayout title="Application settings" description="Configure TaxIO defaults, integrations, and lifecycle." back={{ label: "TaxIO overview", href: "/applications/taxio" }} items={applicationItems} active={active} onSelect={setActive}>
    {active === "general" && <Section title="General" description="Basic identity and default environment for this application." footer={<SaveFooter />}><div className="grid gap-5 sm:grid-cols-[100px_1fr]"><div><span className="grid size-20 place-items-center rounded-2xl bg-accent text-xl font-bold text-accent-foreground">TX</span><Button variant="outline" size="sm" className="mt-3">Change icon</Button></div><div className="space-y-5"><Field label="Application name"><input className="hf-field" defaultValue="TaxIO" /></Field><Field label="Description"><textarea className="hf-field min-h-24 resize-none" defaultValue="Nigerian personal income tax platform" /></Field><Field label="Default environment"><select className="hf-field"><option>Production</option><option>Staging</option><option>Development</option></select></Field></div></div></Section>}
    {active === "git" && <Section title="Git integration" description="Control the default GitHub installation and repository access." footer={<SaveFooter />}><Field label="Default GitHub installation"><select className="hf-field"><option>Mr Fury · 18 repositories</option></select></Field><div className="overflow-hidden rounded-lg border"><SettingRow icon={GithubLogoIcon} title="Repository access" detail="All repositories available to the Mr Fury installation" action="Manage" /><SettingRow icon={KeyIcon} title="Fallback credentials" detail="No personal access token configured" action="Add credential" /><SettingRow icon={ShieldCheckIcon} title="Webhook permissions" detail="Contents read · deployments write · metadata read" action="Review" /></div></Section>}
    {active === "environment" && <Section title="Environment and secrets" description="Defaults for shared configuration inherited by services."><Toggle label="Encrypt all new values by default" description="New application variables will be marked secret unless explicitly changed." defaultOn /><Toggle label="Allow service overrides" description="Services may override variables inherited from this application." defaultOn /><div className="flex items-center gap-3 rounded-lg border bg-muted/35 p-4"><BracketsCurlyIcon size={18} /><div><p className="text-xs font-semibold">4 shared variables configured</p><p className="mt-1 text-[11px] text-muted-foreground">3 secrets · inherited by 3 services</p></div><Button variant="outline" size="sm" className="ml-auto" onClick={() => navigateTo("/applications/taxio/environment")}>Manage variables</Button></div></Section>}
    {active === "activity" && <Section title="Application activity" description="Configuration changes, deployment events, and operator actions."><div className="divide-y rounded-lg border">{[{ title: "Application description changed", detail: "Mr Fury · General settings", time: "18m ago" }, { title: "Shared variable updated", detail: "SENTRY_DSN · value remains hidden", time: "2h ago" }, { title: "Deployment completed", detail: "api · dep_7H3KD9", time: "3h ago" }, { title: "Domain added", detail: "staging.taxio.ng · web", time: "1d ago" }].map((event) => <div key={event.title} className="flex gap-3 px-4 py-3.5"><ActivityIcon size={15} className="mt-0.5 text-muted-foreground" /><div><p className="text-xs font-medium">{event.title}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{event.detail}</p></div><span className="ml-auto text-[10px] text-muted-foreground">{event.time}</span></div>)}</div></Section>}
    {active === "danger" && <DangerSection title="Application danger zone" description="These operations affect TaxIO and every resource contained within it."><DangerAction icon={ArchiveIcon} title="Archive application" description="Hide TaxIO from active views and stop automatic deployments. Services remain available until stopped." action="Archive TaxIO" /><div className="rounded-lg border border-red-200 bg-red-50 p-4"><div className="flex gap-3"><TrashIcon size={19} className="mt-0.5 shrink-0 text-red-700" /><div><p className="text-xs font-semibold text-red-900">Delete TaxIO permanently</p><p className="mt-1 text-[11px] leading-5 text-red-700">Deletion removes all application resources and cannot be undone:</p><ul className="mt-3 grid gap-2 text-[11px] text-red-800 sm:grid-cols-2"><li>3 services and their configuration</li><li>184 deployment records and logs</li><li>4 domains and Caddy routes</li><li>4 shared environment variables</li><li>Running containers and images</li><li>Application activity history</li></ul><Button className="mt-4 bg-red-700 text-white hover:bg-red-800">Delete TaxIO</Button></div></div></div></DangerSection>}
  </SettingsLayout>
}

const serviceItems: SettingsItem[] = [
  { id: "general", label: "General", icon: SlidersHorizontalIcon },
  { id: "source", label: "Source", icon: GithubLogoIcon },
  { id: "build", label: "Build", icon: CodeIcon },
  { id: "runtime", label: "Runtime", icon: PulseIcon },
  { id: "credentials", label: "Git credentials", icon: KeyIcon },
  { id: "danger", label: "Danger zone", icon: WarningCircleIcon },
]

export function ServiceSettings({ service = "api" }: { service?: string }) {
  const [active, setActive] = useState("general")
  return <SettingsLayout title="Service settings" description={`Configure source, build, and runtime behavior for TaxIO/${service}.`} back={{ label: `${service} overview`, href: `/applications/taxio/services/${service}` }} items={serviceItems} active={active} onSelect={setActive}>
    {active === "general" && <Section title="General" description="Service identity and deployable type." footer={<SaveFooter />}><Field label="Service name"><input className="hf-field" defaultValue={service} /></Field><Field label="Service type"><select className="hf-field"><option>Web service</option><option>Worker</option><option>Scheduled job</option><option>Static site</option></select></Field><Field label="Description"><textarea className="hf-field min-h-24 resize-none" defaultValue="Tax assessment and taxpayer API" /></Field></Section>}
    {active === "source" && <Section title="Source" description="Repository, branch, and automatic deployment behavior." footer={<SaveFooter />}><Field label="Repository"><div className="relative"><GithubLogoIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={16} /><input className="hf-field pl-9" defaultValue="mr-fury/taxio" /></div></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Branch"><input className="hf-field font-mono" defaultValue="main" /></Field><Field label="Root directory"><input className="hf-field font-mono" defaultValue="apps/api" /></Field></div><Toggle label="Auto-deploy" description="Start a deployment when the selected branch receives a push." defaultOn /></Section>}
    {active === "build" && <Section title="Build" description="Image build strategy and process commands." footer={<SaveFooter />}><Field label="Build method"><select className="hf-field"><option>Nixpacks · auto-detected</option><option>Dockerfile</option><option>Custom commands</option></select></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Build command"><input className="hf-field font-mono" defaultValue="npm run build" /></Field><Field label="Start command"><input className="hf-field font-mono" defaultValue="npm run start" /></Field></div><Field label="Build context"><input className="hf-field font-mono" defaultValue="." /></Field></Section>}
    {active === "runtime" && <Section title="Runtime" description="Container networking, restart, and health-check policy." footer={<SaveFooter />}><div className="grid gap-5 sm:grid-cols-2"><Field label="Internal port"><input className="hf-field font-mono" defaultValue="3000" /></Field><Field label="Restart policy"><select className="hf-field"><option>Unless stopped</option><option>On failure</option><option>Never</option></select></Field><Field label="Health-check path"><input className="hf-field font-mono" defaultValue="/health" /></Field><Field label="Health-check timeout"><select className="hf-field"><option>30 seconds</option><option>60 seconds</option></select></Field></div></Section>}
    {active === "credentials" && <Section title="Git credentials" description="Choose how HostForge authenticates to this repository."><div className="space-y-3"><CredentialOption selected icon={GithubLogoIcon} title="GitHub App" detail="Mr Fury installation · recommended" /><CredentialOption icon={PasswordIcon} title="Personal access token" detail="No token configured" /><CredentialOption icon={KeyIcon} title="SSH deploy key" detail="No deploy key selected" /></div></Section>}
    {active === "danger" && <DangerSection title="Service danger zone" description={`These actions affect the TaxIO/${service} runtime and history.`}><DangerAction icon={PulseIcon} title="Stop service" description="Stop the active container and remove this service from routing. Configuration is preserved." action="Stop service" /><DangerAction icon={PlugsConnectedIcon} title="Disconnect repository" description="Remove source credentials and disable automatic deployments. Existing deployments remain." action="Disconnect repository" /><DangerAction icon={TrashIcon} title="Delete service" description="Permanently delete configuration, deployments, domains, logs, and the running container for this service." action="Delete service" destructive /></DangerSection>}
  </SettingsLayout>
}

const globalItems: SettingsItem[] = [
  { id: "account", label: "Account", icon: UserCircleIcon },
  { id: "github", label: "GitHub App", icon: GithubLogoIcon },
  { id: "webhooks", label: "Webhooks", icon: WebhooksLogoIcon },
  { id: "networking", label: "Networking & DNS", icon: GlobeIcon },
  { id: "caddy", label: "Caddy", icon: ShieldCheckIcon },
  { id: "deployments", label: "Deployments", icon: CloudArrowUpIcon },
  { id: "system", label: "System", icon: HardDrivesIcon },
  { id: "preferences", label: "Preferences", icon: SlidersHorizontalIcon },
  { id: "about", label: "About", icon: InfoIcon },
]

export function GlobalSettings() {
  const [active, setActive] = useState("account")
  return <SettingsLayout title="Settings" description="Configure the HostForge control plane and operator experience." items={globalItems} active={active} onSelect={setActive}>
    {active === "account" && <Section title="Operator account" description="Account identity, password, and active session information." footer={<SaveFooter />}><div className="grid gap-5 sm:grid-cols-2"><Field label="Username"><input className="hf-field" defaultValue="mr_fury" /></Field><Field label="Display name"><input className="hf-field" defaultValue="Mr Fury" /></Field></div><div className="overflow-hidden rounded-lg border"><SettingRow icon={LockKeyIcon} title="Password" detail="Last changed 18 days ago" action="Change password" /><SettingRow icon={ActivityIcon} title="Current session" detail="WSL2 · 127.0.0.1 · active now" action="Sign out others" /></div></Section>}
    {active === "github" && <Section title="GitHub App" description="Configuration status, installations, and repository access."><StatusHeader title="GitHub App connected" detail="App ID 1849201 · webhook deliveries active" /><div className="overflow-hidden rounded-lg border"><SettingRow icon={GithubLogoIcon} title="Mr Fury" detail="18 repositories · synced 4 minutes ago" action="Sync" /><SettingRow icon={GithubLogoIcon} title="HostForge Organization" detail="6 repositories · synced 12 minutes ago" action="Sync" /></div><div className="flex flex-wrap gap-2"><Button variant="outline">Open manifest setup</Button><Button variant="outline">Sync installations</Button><Button className="bg-red-700 text-white hover:bg-red-800">Delete configuration</Button></div></Section>}
    {active === "webhooks" && <Section title="Webhooks" description="Ingress URL, secret state, and recent delivery health."><Field label="Webhook URL"><div className="flex"><input className="hf-field rounded-r-none font-mono" readOnly value="https://hostforge.example.com/hooks/github" /><Button variant="outline" className="rounded-l-none">Copy</Button></div></Field><div className="grid gap-3 sm:grid-cols-2"><StatusCard icon={KeyIcon} title="Webhook secret" value="Configured" healthy /><StatusCard icon={PulseIcon} title="Ingress probe" value="Passing · 82ms" healthy /></div><div className="overflow-hidden rounded-lg border"><SettingRow icon={CheckCircleIcon} title="push · TaxIO/api" detail="HTTP 202 · 3 minutes ago" action="Inspect" /><SettingRow icon={CheckCircleIcon} title="installation_repositories" detail="HTTP 200 · 12 minutes ago" action="Inspect" /></div></Section>}
    {active === "networking" && <Section title="Networking and DNS" description="Public platform identity and detected host network information." footer={<SaveFooter />}><Field label="Platform domain"><input className="hf-field" defaultValue="hostforge.example.com" /></Field><div className="grid gap-3 sm:grid-cols-2"><StatusCard icon={GlobeIcon} title="Public IPv4" value="197.210.53.184" healthy /><StatusCard icon={ShieldCheckIcon} title="Platform DNS" value="A record verified" healthy /></div><div className="rounded-lg border bg-muted/35 p-4"><p className="text-xs font-semibold">Required DNS record</p><p className="mt-2 font-mono text-[11px]">A · hostforge.example.com · 197.210.53.184</p></div></Section>}
    {active === "caddy" && <Section title="Caddy" description="Reverse-proxy configuration, validation, and route synchronization."><StatusHeader title="Caddy configuration valid" detail="19 active routes · last synchronized 3 minutes ago" /><div className="flex flex-wrap gap-2"><Button variant="outline"><CheckCircleIcon />Validate configuration</Button><Button><ArrowsIcon />Sync routes</Button></div><div className="overflow-hidden rounded-lg border"><SettingRow icon={GlobeIcon} title="Application routes" detail="18 routes active" action="View" /><SettingRow icon={ShieldCheckIcon} title="Platform route" detail="hostforge.example.com · TLS active" action="View" /></div></Section>}
    {active === "deployments" && <Section title="Deployment defaults" description="Default build, health, timeout, and retention preferences." footer={<SaveFooter />}><div className="grid gap-5 sm:grid-cols-2"><Field label="Default build method"><select className="hf-field"><option>Auto-detect with Nixpacks</option><option>Dockerfile</option></select></Field><Field label="Deployment timeout"><select className="hf-field"><option>20 minutes</option><option>30 minutes</option></select></Field><Field label="Health-check timeout"><select className="hf-field"><option>60 seconds</option><option>90 seconds</option></select></Field><Field label="Deployment retention"><select className="hf-field"><option>Keep 30 deployments</option><option>Keep 90 deployments</option></select></Field></div><Toggle label="Prune old build images" description="Remove unreferenced images after retention cleanup." defaultOn /></Section>}
    {active === "system" && <Section title="System" description="Host, Docker, build engine, and current resource state."><div className="grid gap-3 sm:grid-cols-2"><StatusCard icon={HardDrivesIcon} title="Host" value="Ubuntu 24.04 · 4 cores · 16 GB" healthy /><StatusCard icon={CubeIcon} title="Docker" value="27.2.0 · 34 containers" healthy /><StatusCard icon={WrenchIcon} title="Build engine" value="Nixpacks 1.36.0 · operational" healthy /><StatusCard icon={ActivityIcon} title="Resources" value="CPU 28% · Memory 61% · Disk 43%" healthy /></div><Button variant="outline"><ActivityIcon />Refresh system status</Button></Section>}
    {active === "preferences" && <Section title="Preferences" description="Defaults for navigation, tables, time, and motion." footer={<SaveFooter />}><Field label="Default landing page"><select className="hf-field"><option>Overview</option><option>Applications</option><option>Observability</option></select></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Table page size"><select className="hf-field"><option>25 rows</option><option>50 rows</option><option>100 rows</option></select></Field><Field label="Time format"><select className="hf-field"><option>24-hour</option><option>12-hour</option></select></Field></div><Toggle label="Reduced motion" description="Limit non-essential transitions and animated status indicators." /></Section>}
    {active === "about" && <Section title="About HostForge" description="Version, build information, documentation, and licensing."><div className="flex items-center gap-4 rounded-lg border bg-muted/30 p-5"><span className="grid size-12 place-items-center rounded-xl bg-accent text-accent-foreground"><CubeIcon size={23} weight="fill" /></span><div><p className="text-sm font-semibold">HostForge v0.9.4</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">build 7f28c91 · Go 1.25 · UI 2026.07</p></div></div><div className="overflow-hidden rounded-lg border"><SettingRow icon={BookOpenIcon} title="Documentation" detail="Operator and development guides" action="Open" /><SettingRow icon={CodeIcon} title="Source license" detail="Apache License 2.0" action="View license" /><SettingRow icon={InfoIcon} title="Build information" detail="linux/amd64 · embedded Vite assets" action="Copy" /></div></Section>}
  </SettingsLayout>
}

function DangerSection({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="overflow-hidden rounded-xl border border-red-200 bg-card"><header className="border-b border-red-200 bg-red-50 px-5 py-4"><h2 className="text-sm font-semibold text-red-900">{title}</h2><p className="mt-1 text-xs text-red-700">{description}</p></header><div className="space-y-4 p-5">{children}</div></section> }
function DangerAction({ icon: Icon, title, description, action, destructive = false }: { icon: React.ComponentType<{ size?: number; className?: string }>; title: string; description: string; action: string; destructive?: boolean }) { return <div className="flex flex-col gap-4 rounded-lg border border-red-200 p-4 sm:flex-row sm:items-center"><Icon size={19} className="shrink-0 text-red-700" /><div><p className="text-xs font-semibold text-red-900">{title}</p><p className="mt-1 text-[11px] leading-5 text-red-700">{description}</p></div><Button variant={destructive ? "default" : "outline"} className={`sm:ml-auto ${destructive ? "bg-red-700 text-white hover:bg-red-800" : "border-red-300 text-red-700"}`}>{action}</Button></div> }
function SettingRow({ icon: Icon, title, detail, action }: { icon: React.ComponentType<{ size?: number; className?: string }>; title: string; detail: string; action: string }) { return <div className="flex items-center gap-3 border-b px-4 py-3.5 last:border-b-0"><span className="grid size-8 shrink-0 place-items-center rounded-md border bg-muted"><Icon size={15} /></span><div className="min-w-0"><p className="text-xs font-semibold">{title}</p><p className="mt-0.5 truncate text-[10px] text-muted-foreground">{detail}</p></div><Button variant="ghost" size="sm" className="ml-auto">{action}</Button></div> }
function CredentialOption({ selected = false, icon: Icon, title, detail }: { selected?: boolean; icon: React.ComponentType<{ size?: number; className?: string }>; title: string; detail: string }) { return <button className={`flex w-full items-center gap-3 rounded-lg border p-4 text-left ${selected ? "border-foreground bg-muted/50 ring-1 ring-foreground" : "hover:bg-muted/30"}`}><Icon size={18} /><div><p className="text-xs font-semibold">{title}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{detail}</p></div>{selected && <CheckCircleIcon className="ml-auto" size={17} weight="fill" />}</button> }
function StatusHeader({ title, detail }: { title: string; detail: string }) { return <div className="flex items-center gap-3 rounded-lg border border-emerald-200 bg-emerald-50 p-4"><CheckCircleIcon size={20} weight="fill" className="text-emerald-700" /><div><p className="text-xs font-semibold text-emerald-900">{title}</p><p className="mt-1 text-[10px] text-emerald-700">{detail}</p></div></div> }
function StatusCard({ icon: Icon, title, value, healthy }: { icon: React.ComponentType<{ size?: number; className?: string }>; title: string; value: string; healthy?: boolean }) { return <div className="flex items-center gap-3 rounded-lg border p-4"><span className="grid size-9 place-items-center rounded-lg bg-muted"><Icon size={17} /></span><div><p className="text-[10px] text-muted-foreground">{title}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>{healthy && <CheckCircleIcon className="ml-auto text-emerald-600" size={16} weight="fill" />}</div> }
function ArrowsIcon() { return <ActivityIcon /> }
